Continue building bootstrap-tools

diff --git a/bootstrap/bootstrap-tools b/bootstrap/bootstrap-tools
--- a/bootstrap/bootstrap-tools
+++ b/bootstrap/bootstrap-tools
@@ -6,21 +6,18 @@ set -e
 # Check for xcode-CLT
 echo ""
 echo "Checking for Command Line Tools..."
-if [ "$(
-	xcode-select -p 2>/dev/null
-	echo $?
-)" = "2" ]; then
+if [ "$(xcode-select -p 2>/dev/null; echo $?)" = "2" ]; then
 	echo "Command Line Tools not found. Installing now..."
 	touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
 	PROD=$(softwareupdate -l |
-		grep "\*.*Command Line" |
-		head -n 1 | awk -F"*" '{print $2}' |
-		sed -e 's/^ *//' |
-		tr -d '\n')
+		       grep "\*.*Command Line" |
+		       head -n 1 | awk -F"*" '{print $2}' |
+		       sed -e 's/^ *//' |
+		       tr -d '\n')
 	softwareupdate -i "$PROD" --verbose
 	rm /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
 else
-	echo "Command Line Tools already installed at: $(xcode-select --print-path)"
+	echo "CLT already installed at: $(xcode-select --print-path)"
 	echo ""
 fi
 
@@ -30,83 +27,72 @@ if [[ ! -e "$(which brew)" ]]; then
 	echo "Homebrew not found. Installing Now..."
 	ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
 else
-	echo "Homebrew Installed. Updating now..."
+	echo "Homebrew installed. Updating now..."
 	echo ""
 	brew upgrade
 fi
 
 echo "Please select a default shell:"
 PS3="> "
-options=("Zsh" "Bash" "Fish" "Skip Shell Configuration")
+options=("zsh" "bash" "fish" "skip shell config")
 
 select opt in "${options[@]}"; do
 	case "$REPLY" in
-
-	1)
-		echo ""
-		echo "Setting up $opt..."
-		break
-		;;
-	2)
-		echo ""
-		echo "Setting up $opt..."
-		break
-		;;
-	3)
-		echo ""
-		echo "Setting up $opt..."
-		break
-		;;
-	4)
-		echo ""
-		echo "Skipping Shell Config..."
-		break
-		;;
-	*)
-		echo "Invalid option. Try another one."
-		continue
-		;;
+	1) echo ""; echo "Setting up $opt..."; break;;
+	2) echo "";	echo "Setting up $opt..."; break;;
+	3) echo ""; echo "Setting up $opt..."; break;;
+	4) echo ""; echo "Skipping Shell Config..."; break;;
+	*) echo "Invalid option. Try another one."; continue;;
 	esac
 done
 
-if [ $opt = "Zsh" ]; then
-	if test ! -e /usr/local/bin/zsh; then
-		echo "Installing latest version of ZSH from homebrew"
-		echo ""
-		brew install zsh
-	fi
+if [ "$REPLY" != "4" ]; then
+    status="…"
+    echo -ne "==> Checking for $opt installation - $status"\\r
+    if test ! -e "/usr/local/bin/$opt"; then
+        status="✘"
+        echo "==> Checking for $opt installation - $status"
+	    echo "Installing latest version of $opt from homebrew"
+	    echo ""
+	    brew install $opt
+    else
+        status="🗸"
+        echo "==> Checking for $opt installation - $status"
+    fi
 
-	if ! grep -Fxq "/usr/local/bin/zsh" /etc/shells; then
-		echo "Adding /usr/local/bin/zsh to /etc/shells file"
-		echo ""
-		echo '/usr/local/bin/zsh' | sudo tee -a /etc/shells
-	else
-		echo "/usr/local/bin/zsh already in /etc/shells..."
-		echo ""
-	fi
+    status="…"
+    echo -ne "==> Checking /etc/shells - $status"\\r
+    if ! grep -Fxq "/usr/local/bin/$opt" /etc/shells; then
+        status="✘"
+        echo "==> Checking /etc/shells - $status"
+	    echo "Adding /usr/local/bin/$opt to /etc/shells file"
+	    echo '/usr/local/bin/$opt' | tee -a /etc/shells
+    else
+        status="🗸"
+        echo "==> Checking /etc/shells - $status"
+    fi
 
-	if [ "$SHELL" != "/usr/local/bin/zsh" ]; then
-		chsh -s /usr/local/bin/zsh
-		echo "ZSH is now your default shell. Please restart your terminal once this script has finished"
-	fi
+    status="…"
+    echo -ne "==> Checking \$SHELL - $status"\\r
+    if [ "$SHELL" != "/usr/local/bin/$opt" ]; then
+        status="✘"
+        echo "==> Checking \$SHELL - $status"
+	    chsh -s "/usr/local/bin/$opt"
+	    echo "$opt is now your default shell. Please restart your terminal once this script has finished"
+    else
+        status="🗸"
+        echo "==> Checking \$SHELL - $status"
+    fi
 fi
 
+echo ""
 echo "Would you like to upgrade/install dependencies from Brewfile? "
 PS3="> "
 select opt in "Yes" "No"; do
 	case "$REPLY" in
-	1)
-		echo "Installing Brewfile..."
-		break
-		;;
-	2)
-		echo "Skipping Brewfile install..."
-		break
-		;;
-	*)
-		echo "Invalid option. 1 for Yes, 2 for No"
-		continue
-		;;
+	1) echo "Installing Brewfile..."; break;;
+	2) echo "Skipping Brewfile install..."; break;;
+	*) echo "Invalid option. 1 for Yes, 2 for No"; continue;;
 	esac
 done
 
